language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - python -m pytest ./veritorch/test/test.py --cov --cov-report term-missing
after_success:
    - codecov
