language: python
python:
    - "3.6"
before_install:
    - pip install -U pip
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest ./veritorch/test/test.py --cov --cov-report term-missing
after_success:
    - codecov
